name: build, package and deploy

on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'
      - '.github/workflows/release.yml'
permissions:
  contents: read
jobs:
  build:
    if: github.repository == 'rstreamlabs/rstream-js'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        shell: bash
        run: |
          npm ci
      - name: Build packages
        shell: bash
        run: |
          npm run build
      - name: Create release PR or publish to NPM
        id: changesets
        uses: changesets/action@63a615b9cd06ba9a3e6d13796c7fbcb080a60a0b # v1.8.0
        with:
          version: npm run ci:version
          publish: npm run ci:release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_IGNORE_SCRIPTS: "true"
